# Generated by Django 5.0 on 2023-12-06 18:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название книги')),
                ('publicated_at', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.ManyToManyField(related_name='book', to='core.author', verbose_name='Автор(ы)')),
                ('favorite_for', models.ManyToManyField(related_name='favorite_book', to=settings.AUTH_USER_MODEL, verbose_name='Избранное у пользователей')),
                ('genre', models.ManyToManyField(related_name='book', to='core.genre', verbose_name='Жанр(ы)')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг')),
                ('feedback_text', models.TextField(verbose_name='Текст отзыва')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='core.book', verbose_name='На книгу')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to=settings.AUTH_USER_MODEL, verbose_name='Кем оставлен отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'unique_together': {('book', 'created_by')},
            },
        ),
    ]
