# Generated by Django 5.0 on 2023-12-06 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='favorite_for',
            field=models.ManyToManyField(blank=True, related_name='favorite_book', to=settings.AUTH_USER_MODEL, verbose_name='Избранное у пользователей'),
        ),
    ]
