# Generated by Django 5.0 on 2023-12-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_book_favorite_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publicated_at',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
