# Generated by Django 5.0 on 2023-12-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_publicated_at_book_publicated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
